---
title: "Dashboard COVID Data Prep"
author: "RQ"
date: "16/07/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(readr)
library(dplyr)
```

This Rmarkdown document steps through the preparation of the COVID19 data on the 
frontpage of the airport dasboards.

```
TO-DO: check back with Muriel to produce data for APDF airports not in top100.
```
Read in latest COVID file(s) from Muriel.

* download 1_Top_100_Airport_dep+arr_LTFM+LTBA (Synthesis).xlsx
  save as COVID-AIRPORT.xlsx

```{r}
ds <- readxl::read_excel(
   path = "./data/COVID-AIRPORT.xlsx"
  ,sheet= "DATA", range = cell_cols("O:X"), skip = 10)

nms <- readxl::read_excel(
   path = "./data/COVID-AIRPORT.xlsx"
  ,sheet= "MAP_STATE_AIRPORT", range = cell_cols("B:D")) %>%
  # add header col to find and filter empty cells not captured correctly
  # du to merge cell (i.e. skip = x) stumbles over cell with formula
  mutate( HEADER = if_else(.[[1]] == "ARP_NAME", 1, 0)
         ,HEADER = tidyr::replace_na(HEADER, 0)
         ,HEADER = cumsum(HEADER)) %>%
  filter(HEADER == 1)
  # delete column
  nms$HEADER <- NULL
  #now make first row the header row and remove it
names(nms) <- nms[1,]
nms <- nms[-1,]

ds <- ds %>% rename(
   "ARP_NAME" = "Entity", "WEEK" = "Week", "DAY" = "Day"
  ,"FLTS_2019" = "Flights 2019", "FLTS_2020" = "Flights 2020"
  ,"VAR_DLY" = "Daily Variation", "VAR_WKLY" = "Weekly Variation"
  ,"MOV_AVG_WK" = "Weekly Moving Average"
  #,"DAY2019" = "...11"
  )

# merge ICAO with ds
ds <- ds %>% left_join(nms, by = "ARP_NAME") %>%
  rename(APT_ICAO = ARP_CODE)
```

Save-out COVID data for front-page     
filtering for dashboard done by trim_covid() function

```{r}
write_csv(ds, "./data/COVID_AIRPORT.csv")
```

